import JSZip from 'jszip';
import type { EmitterParams, TextureSource } from './configGenerator';
import type { EmissionMaskData } from '../types/emissionMask';
import type { ParticleSpriteType } from './spriteGenerator';
import { exportProceduralParticlePng } from './spriteGenerator';
import { generateBoilerplateJS } from './exporter';

export interface VfxPackageExportInput {
  particleName: string;
  params: EmitterParams;
  textureSource: TextureSource;
  particleSpriteType: ParticleSpriteType;
  selectedParticleTextureId: string;
  customParticleSpriteUrl: string | null;
  libraryParticleTextureUrl: string | null;
  symbolImageUrl: string | null;
  emitterConfig: object;
  winStatesExport: object | null;
  timelineExport: object;
  emissionMask: EmissionMaskData | null;
}

interface AssetBytes {
  data: Uint8Array;
  mime: string;
  ext: string;
}

function mimeToExt(mime: string): string {
  const map: Record<string, string> = {
    'image/png': 'png',
    'image/jpeg': 'jpg',
    'image/jpg': 'jpg',
    'image/webp': 'webp'
  };
  return map[mime] ?? 'png';
}

function extFromUrl(url: string): string | null {
  const clean = url.split('?')[0]?.split('#')[0] ?? url;
  const match = clean.match(/\.([a-zA-Z0-9]+)$/);
  return match ? match[1].toLowerCase() : null;
}

async function assetUrlToBytes(url: string): Promise<AssetBytes> {
  if (url.startsWith('data:')) {
    const commaIndex = url.indexOf(',');
    const header = url.slice(0, commaIndex);
    const body = url.slice(commaIndex + 1);
    const mime = header.match(/data:([^;]+)/)?.[1] ?? 'application/octet-stream';
    const isBase64 = header.includes(';base64');

    let data: Uint8Array;
    if (isBase64) {
      const binary = atob(body);
      data = new Uint8Array(binary.length);
      for (let i = 0; i < binary.length; i++) {
        data[i] = binary.charCodeAt(i);
      }
    } else {
      data = new TextEncoder().encode(decodeURIComponent(body));
    }

    return { data, mime, ext: mimeToExt(mime) };
  }

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch asset: ${url}`);
  }

  const blob = await response.blob();
  const mime = blob.type || 'application/octet-stream';
  const data = new Uint8Array(await blob.arrayBuffer());
  const ext = extFromUrl(url) ?? mimeToExt(mime);

  return { data, mime, ext };
}

function patchEmitterConfigTexturePath(config: any, texturePath: string): any {
  if (!config?.behaviors) return config;

  return {
    ...config,
    behaviors: config.behaviors.map((behavior: any) =>
      behavior.type === 'textureSingle'
        ? {
            ...behavior,
            config: {
              ...behavior.config,
              texture: texturePath
            }
          }
        : behavior
    )
  };
}

function patchWinStatesExport(exportData: any, texturePath: string) {
  if (!exportData?.states) return exportData;

  const states: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(exportData.states as Record<string, any>)) {
    states[key] = {
      ...value,
      emitterConfig: patchEmitterConfigTexturePath(value.emitterConfig, texturePath)
    };
  }

  return { ...exportData, states };
}

function patchTimelineExport(exportData: any, texturePath: string) {
  if (!exportData?.patches) return exportData;

  return {
    ...exportData,
    patches: exportData.patches.map((patch: any) => ({
      ...patch,
      configPatch: patchEmitterConfigTexturePath(patch.configPatch, texturePath)
    }))
  };
}

function buildReadme(particleName: string, manifest: Record<string, unknown>): string {
  return `PixiVFX Weaver — VFX Package
Symbol: ${particleName}
Exported: ${manifest.exportedAt}

Folder layout:
  config/     Emitter JSON, params snapshot, win states, timeline
  scripts/    Ready-to-use PixiJS integration (vfx-emitter.js)
  textures/   Particle sprite + slot symbol reference image
  manifest.json
  README.txt

Quick start:
  1. Load textures/particle.* as PIXI.Texture in your game.
  2. Import scripts/${particleName}-vfx-emitter.js or read config/${particleName}-emitter.json.
  3. Point textureSingle behavior to the bundled particle texture path.

Generated by PixiVFX_Weaver (PixiJS v7 + @pixi/particle-emitter)
`;
}

async function resolveParticleTexture(input: VfxPackageExportInput): Promise<{
  filename: string;
  bytes: Uint8Array;
  source: string;
}> {
  switch (input.textureSource) {
    case 'custom': {
      if (!input.customParticleSpriteUrl) {
        throw new Error('Custom particle sprite is not loaded.');
      }
      const asset = await assetUrlToBytes(input.customParticleSpriteUrl);
      return {
        filename: `particle.${asset.ext}`,
        bytes: asset.data,
        source: 'custom upload'
      };
    }
    case 'library': {
      if (!input.libraryParticleTextureUrl) {
        throw new Error('Library particle texture is not selected.');
      }
      const asset = await assetUrlToBytes(input.libraryParticleTextureUrl);
      return {
        filename: `particle.${asset.ext}`,
        bytes: asset.data,
        source: `library:${input.selectedParticleTextureId}`
      };
    }
    case 'symbol': {
      if (!input.symbolImageUrl) {
        throw new Error('Symbol image is required when particle texture source is Symbol.');
      }
      const asset = await assetUrlToBytes(input.symbolImageUrl);
      return {
        filename: `particle.${asset.ext}`,
        bytes: asset.data,
        source: 'symbol image'
      };
    }
    default: {
      const bytes = await exportProceduralParticlePng(input.particleSpriteType);
      return {
        filename: 'particle.png',
        bytes,
        source: `procedural:${input.particleSpriteType}`
      };
    }
  }
}

export async function buildVfxPackageZip(input: VfxPackageExportInput): Promise<Blob> {
  const zip = new JSZip();
  const rootName = `${input.particleName}-vfx`;
  const root = zip.folder(rootName);
  if (!root) {
    throw new Error('Failed to create zip folder.');
  }

  const configFolder = root.folder('config');
  const scriptsFolder = root.folder('scripts');
  const texturesFolder = root.folder('textures');
  if (!configFolder || !scriptsFolder || !texturesFolder) {
    throw new Error('Failed to create zip subfolders.');
  }

  const particle = await resolveParticleTexture(input);
  texturesFolder.file(particle.filename, particle.bytes);

  const textureRelativePath = `../textures/${particle.filename}`;

  let symbolFilename: string | null = null;
  if (input.symbolImageUrl && input.textureSource !== 'symbol') {
    const symbolAsset = await assetUrlToBytes(input.symbolImageUrl);
    symbolFilename = `symbol.${symbolAsset.ext}`;
    texturesFolder.file(symbolFilename, symbolAsset.data);
  } else if (input.symbolImageUrl && input.textureSource === 'symbol') {
    symbolFilename = particle.filename;
  }

  const patchedEmitter = patchEmitterConfigTexturePath(input.emitterConfig, textureRelativePath);
  const paramsSnapshot = { ...input.params, textureName: input.particleName };

  configFolder.file(`${input.particleName}-emitter.json`, JSON.stringify(patchedEmitter, null, 2));
  configFolder.file(`${input.particleName}-params.json`, JSON.stringify(paramsSnapshot, null, 2));

  if (input.winStatesExport) {
    configFolder.file(
      `${input.particleName}-vfx-states.json`,
      JSON.stringify(patchWinStatesExport(input.winStatesExport, textureRelativePath), null, 2)
    );
  }

  configFolder.file(
    `${input.particleName}-timeline.json`,
    JSON.stringify(patchTimelineExport(input.timelineExport, textureRelativePath), null, 2)
  );

  if (input.emissionMask && input.emissionMask.mode !== 'point') {
    configFolder.file(`${input.particleName}-emission-mask.json`, JSON.stringify(input.emissionMask, null, 2));
  }

  scriptsFolder.file(
    `${input.particleName}-vfx-emitter.js`,
    generateBoilerplateJS(paramsSnapshot, patchedEmitter)
  );

  const manifest = {
    generator: 'PixiVFX_Weaver',
    version: '1.0',
    exportedAt: new Date().toISOString(),
    symbol: input.particleName,
    preset: input.params.preset,
    textureSource: input.textureSource,
    particleTexture: {
      filename: particle.filename,
      source: particle.source
    },
    symbolTexture: symbolFilename ? { filename: symbolFilename } : null,
    emissionMask: input.emissionMask?.mode ?? 'point',
    files: {
      emitter: `config/${input.particleName}-emitter.json`,
      params: `config/${input.particleName}-params.json`,
      states: input.winStatesExport ? `config/${input.particleName}-vfx-states.json` : null,
      timeline: `config/${input.particleName}-timeline.json`,
      emissionMask:
        input.emissionMask && input.emissionMask.mode !== 'point'
          ? `config/${input.particleName}-emission-mask.json`
          : null,
      script: `scripts/${input.particleName}-vfx-emitter.js`,
      particleTexture: `textures/${particle.filename}`,
      symbolTexture: symbolFilename ? `textures/${symbolFilename}` : null
    }
  };

  root.file('manifest.json', JSON.stringify(manifest, null, 2));
  root.file('README.txt', buildReadme(input.particleName, manifest));

  return zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 }
  });
}

function triggerBlobDownload(blob: Blob, filename: string) {
  const objectUrl = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = objectUrl;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(objectUrl);
}

export async function downloadVfxPackageZip(input: VfxPackageExportInput): Promise<void> {
  const blob = await buildVfxPackageZip(input);
  triggerBlobDownload(blob, `${input.particleName}-vfx-package.zip`);
}
